spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: user-service

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  refresh-token:
    expiration: 604800000 # 7 days

server:
  port: ${PORT:8083}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3002}
